### ISSUE TITLE
commit 2783e77f934e17a5dc8b15de83cded22a651a560 (fix off-by-one error in the feedback endpoint) causes overflow in ep1_out fifo

### ISSUE THREAD

**Issue by stsrc** [hansfbaier/deca-usb2-audio-interface#4]
Hello,

On Linux (Ubuntu 20.04.3 LTS) latest code (from branch 'main') does not work properly: after 2-3 minutes of normal playback there is loud noise (something like white noise). It is caused by overflow in ep1_out fifo, what leads to malformed state of USBStreamToChannels.

By comparing latest code with version 0.2.0 (on which everything works correctly) I found that commit 2783e77f934e17a5dc8b15de83cded22a651a560 causes such behavior. After revert everything works properly.

I was trying to fix it by my own, but I don't know that much about USB, so I am living this issue to you.

**Comment by hansfbaier** [comment]
Reverted that commit. Thanks for reporting!
