### ISSUE TITLE
protocol error for descriptors longer than 128 bytes

### ISSUE THREAD

**Issue by BrettRD** [hansfbaier/deca-usb2-audio-interface#5]
I've ported this to a ecp5 with a usb3300,
I can get the board to enumerate, but only by cutting the descriptor back.

If I comment out `create_output_streaming_interface()` and `create_input_streaming_interface()`, it enumerates fine with a URB length of 119 bytes.

If I include a single `AudioStreamingInterfaceDescriptorEmitter()` under _either_ the input or output descriptor it also enumerates fine, with a URB length of 128 bytes.

If I include the `AudioStreamingInterfaceDescriptorEmitter()`s in _both_ the input and output descriptors, I get a Protocol Error -71 at the `GET DESCRIPTOR Response DEVICE`  stage, it doesn't get far enough to even report the length of the descriptor.
in dmesg that's a `device descriptor read/64, error -71`

This smells vaguely like https://github.com/greatscottgadgets/luna/issues/86, but I'm definitely running the fix from that.
I'd report this under GSG Luna, but I'm not sure how much I'm leaning on upstream patches from https://github.com/amaranth-community-unofficial/usb2-highspeed-core

**Comment by BrettRD** [comment]
I found a workaround.

adding `os.environ["LUNA_AVOID_BLOCKRAM"] = "True"` immediately after main starts fixes enumeration.

This follows from an optimisation to place the descriptors in block ram.
https://github.com/greatscottgadgets/luna/commit/03607737813f56ba5c944e0d17559e27d8580055#diff-87684f456ce45e8ba3e7202cec537b4a972c1908b54d7a94271445a538c34ea4R49

This patch came after https://github.com/greatscottgadgets/luna/issues/86, and the tests only covered >64 byte descriptors.

I don't know why this fixes it, I'll dig a little deeper and open another issue upstream

**Comment by hansfbaier** [comment]
@BrettRD Thanks for figuring this out! I had no issues with Intel FPGAs here and I did not try the project for Lattice ones yet.
If you do a git log -p on the modules which handle the descriptors, you will likely find out that I didn't change anything there (IIRC).
Can we close this issue here?
